name: MidupBedWars
version: 1.0
main: com.midup.bedwars.Main
author: Cirovx
softdepend: [Midup]
depend: [Citizens]
commands:
    game:
    global:
        aliases:
            - g
            - all
            - shout
            